# aliases

alias k='kubectl'
alias kindmeup='kubectl config use-context kind-kind'
alias ll='ls -lahG'
alias vim='nvim'

# path
export PATH=$PATH:$HOME/go/bin:/usr/local/kubebuilder/bin

# bash-completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# direnv
eval "$(direnv hook bash)"

# private
if [ -f ~/.bash_private ]; then
   source ~/.bash_private
fi
